import {Dimensions, StyleSheet} from 'react-native';

const screen = Dimensions.get('window'),
  vh = screen.height / 100,
  vw = screen.width / 100;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: 100 * vw,
    backgroundColor: '#f5f5f5',
  },
  classContainer: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
  },
  input: {
    paddingTop: 1.5 * vh,
    paddingBottom: 1.5 * vh,
    paddingLeft: 5 * vw,
    paddingRight: 5 * vw,
    margin: vh,
    width: 80 * vw,
    backgroundColor: 'rgba(0,0,0,0.15)',
  },
  dobFields: {
    flexDirection: 'row',
  },
  fieldsInputDate: {
    width: 10 * vw,
    fontSize: 5 * vw,
    backgroundColor: 'transparent',
    paddingLeft: 2 * vw,
    paddingRight: 0,
    paddingBottom: 0.5 * vh,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomColor: '#777',
    borderBottomWidth: 1,
  },
  dateYear: {width: 17 * vw},
  dobFieldsText: {
    margin: 0,
    paddingTop: 2.5 * vh,
    fontSize: 5 * vw,
    paddingLeft: 0,
  },
  fieldsInputName: {
    borderBottomWidth: 1,
    borderBottomColor: '#777',
    fontSize: 5 * vw,
    backgroundColor: 'transparent',
    paddingLeft: 0,
    paddingBottom: 0.5 * vh,
    width: 66 * vw,
  },
  otpInputWrapper: {
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 5 * vh,
  },
  fieldsContinue: {
    backgroundColor: '#a9a9a9',
    height: 7.5 * vh,
    borderRadius: 3.75 * vh,
    marginTop: 5 * vh,
  },
  fieldsContinueText: {
    fontSize: 5 * vw,
  },
  genderTogglesContainer: {
    flexDirection: 'row',
  },
  genderToggle: {
    paddingRight: 5 * vw,
    paddingLeft: 5 * vw,
    backgroundColor: '#a9a9a9',
    width: 32 * vw,
    height: 6 * vh,
    margin: vh,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 3 * vh,
  },
  progressbar:{
    height: 10* vh,
    alignItems: 'center',
    marginTop: 70* vh,
  },
  genderToggleText: {
    fontSize: 5 * vw,
    color: 'white',
  },
  otpInput: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: 4 * vw,
    margin: vh,
    width: 10 * vw,
    backgroundColor: '#b26df2',
    color: 'white',
    fontSize: 5 * vw,
  },
  button: {
    paddingTop: 2 * vh,
    paddingBottom: 2 * vh,
    paddingLeft: 5 * vw,
    paddingRight: 5 * vw,
    marginLeft: vw,
    marginRight: vw,
    marginTop: vh,
    marginBottom: vh,
    width: 40 * vw,
    backgroundColor: '#555',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  button1: {
    paddingTop: 2 * vh,
    paddingBottom: 2 * vh,
    paddingLeft: 5 * vw,
    paddingRight: 5 * vw,
    marginLeft: vw,
    marginRight: vw,
    borderRadius: 10,
    backgroundColor: '#73009e',
    marginTop: vh,
    marginBottom: vh,
    width: 40 * vw,
    
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonclose1: {
    paddingTop: 2 * vh,
    paddingBottom: 2 * vh,
    paddingLeft: 5 * vw,
    paddingRight: 5 * vw,
    marginLeft: 31 * vw,
    marginRight: vw,
    borderRadius: 20,
    backgroundColor: '#df0000',
    marginTop: vh,
    marginBottom: vh,
    width: 40 * vw,
    
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  classButton: {
    borderRadius: 1000,
    width: 30 * vw,
    backgroundColor: 'steelblue'
  },
  boardButton: {
    width: 80 * vw,
    backgroundColor: 'steelblue'
  },
  boardsScroll: {
    flex: 1,
    margin: 20,
  },
  boardsContentScroll: {
    width: '100%',
    alignItems: 'center',

  },
  buttonText: {
    color: 'white',
    fontSize: 16,
  },
  fieldsTitle: {
    fontSize: 7.5 * vw,
    color: '#af64db',
    // position: 'absolute',
    //top: 2 * vh,
  },
  picture: {
    height: 30 * vw,
    width: 30 * vw,
    borderRadius: 15 * vw,
    marginTop: 10 * vh,
    marginBottom: 0.5 * vh,
    borderWidth: 5,
    borderColor: '#ecddfa',
  },
  imageModal: {
    height: 40 * vh,
    width: 80 * vw,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 6 * vw,
    marginTop: 15 * vh,
  },
  sectionHeader: {
    fontSize: 48,
    width: '100%',
    marginTop: 20,
    marginBottom: 20,
    marginLeft: 30,
  },
  fbButtonWrapper: {
    margin: 20,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'blue',
    borderRadius: 2,
    justifyContent: 'center',
    alignItems: 'center',
    height: 40,
    width: 40,
    backgroundColor: 'white',
  },
  boardHeader: {
    position: 'absolute',
    top: 0,
    width: 100 * vw,
    height: 24 * vh,
    backgroundColor: 'coral',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  headerIcon: {
    height: 22 * vw,
    width: 22 * vw,
  },
  boardSelect: {
    position: 'absolute',
    top: 0,
    height: 45 * vh,
    width: 100 * vw,
    justifyContent: 'center',
    alignItems: 'center',
  },
  boardTitle: {
    fontSize: 8 * vw,
    color: 'white',
    marginBottom: 5 * vh,
  },
  boardButtonContainer: {
    height: 7 * vh,
    width: 75 * vw,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  boardToggle: {
    flex: 1,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#e7e7e7',
  },
  activeToggle: {
    backgroundColor: '#bb65dc',
    transform: [
      {scaleX: 1},
      {scaleY: 1},
    ],
    zIndex: 2,
    elevation: 5,
  },
  activeToggleText: {
    color: 'white',
  },
  leftToggle: {
    borderBottomLeftRadius: 3.5 * vh,
    borderTopLeftRadius: 3.5 * vh,
  },
  rightToggle: {
    borderBottomRightRadius: 3.5 * vh,
    borderTopRightRadius: 3.5 * vh,
  },
  boardToggleText: {
    color: '#bb65dc',
    fontSize: 26,
  },
  classSelect: {
    position: 'absolute',
    bottom: 0,
    height: 55 * vh,
    width: 100 * vw,
    borderTopLeftRadius: 5 * vw,
    borderTopRightRadius: 5 * vw,
    backgroundColor: 'white',
    justifyContent: 'flex-start',
    paddingTop: 10 * vh,
    alignItems: 'center'
  },
  classToggle: {
    width: 8 * vh,
    height: 8 * vh,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 4 * vh,
    borderWidth: 1,
    borderColor: '#a673db',
  },
  classToggleText: {
    color: 'black',
    fontSize: 22,
  },
  nextPage: {
    position: 'absolute',
    top: 83.5 * vh,
    left: 0 - 4.5 * vh,
    height: 9 * vh,
    width: 9 * vh,
    borderRadius: 4.5 * vh,
    justifyContent: 'center',
    alignItems: 'center',
  },
  nextPageIcon: {
    height: '100%',
    width: '100%',
  },
  locationIcon: {
    height: 30 * vh,
    width: 60 * vw,
    marginTop: 15 * vh,
  },
  locationTitle: {
    width: 100 * vw,
    textAlign: 'center',
    fontSize: 24,
    marginTop: 5 * vh,
    color: 'black',
  },
  locationTextInputContainer: {
    marginTop: 2.5 * vh,
    width: 85 * vw,
  },
  locationTextInput: {
    width: 90 * vw,
    borderRadius: 5 * vh,
    fontSize: 20,
    height: '100%',
    backgroundColor: '#e4e4e4',
    color: 'black',
    paddingLeft: 5 * vw,
    paddingRight: 5 * vw,
  },
  locationInputWrapper: {
    overflow: 'hidden',
    borderTopWidth: 0,
    borderBottomWidth: 0,
    padding: vh,
    backgroundColor: 'transparent',
    height: 9 * vh,
    justifyContent: 'center',
    alignItems: 'center'
  },
  topNav: {
    width: 100 * vw,
    height: 10 * vh,
    elevation: 1,
    position: 'absolute',
    top: 0,
    backgroundColor: '#f5f5f5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backIcon: {
    height: 5 * vh,
    width: 5 * vh,
    marginLeft: 10 * vw - 2.5 * vh,
    transform: [{rotateZ: '180deg'}],
    position: 'absolute',
    left: 0,
  },
  notificationIcon: {
    height: 4 * vh,
    width: 4 * vh,
    marginRight: 10 * vw - 2 * vh,
    position: 'absolute',
    right: 0,
  },
  topNavTitle: {
    fontSize: 6 * vw,
    position: 'absolute',
    top: 2.5 * vh,
    elevation: 10,
    fontFamily: 'Montserrat-Medium',
    color: 'black',
  },
  subjectCardsContainer: {
    alignItems: 'center',
    paddingTop: 2 * vh,
  },
  subjectCard: {
    height: 27 * vh,
    width: 90 * vw,
    borderRadius: 2 * vw,
    overflow: 'hidden',
    backgroundColor: 'orange',
    marginTop: 1.5 * vh,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  subjectCardsScrollContainer: {
    width: '100%',
    marginTop: 10* vh,
  },
  subjectCardsScrollContainer1: {
    width: '100%',
    marginTop: 3* vh,
  },
  subjectCardBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    height: '100%',
    width: '100%',
  },
  subjectCardIcon: {
    top: 6 * vh,
    height: 15 * vh,
    width: 15 * vh,
    marginLeft: 10 * vw,
    borderRadius: 7.5 * vh,
    borderWidth: vw,
    borderColor: 'rgba(255,255,255,0.5)',
  },
  subjectInfo: {
    justifyContent: 'center',
    marginTop: 5 * vh,
    paddingLeft: 5 * vw,
    flex: 1,
  },
  subjectName: {
    fontSize: 5.25 * vw,
    color: 'white',
    fontFamily: 'Montserrat-SemiBold',
  },
  teacherInfo: {
    fontSize: 3.5 * vw,
    color: 'white',
    fontFamily: 'Montserrat-Medium',
  },
  teacherCarousel: {
    height: 57.5 * vh,
    marginTop: 10 * vh,
    backgroundColor: 'coral'
  },
  teacherCardWrapper: {
    height: 50 * vh,
    width: 60 * vw,
    justifyContent: 'center',
    alignItems: 'center',
  },
  teacherCard: {
    height: 40 * vh,
    width: 50 * vw,
    elevation: 10,
    backgroundColor: 'white',
    borderRadius: 2 * vw,
    alignItems: 'center',
    justifyContent: 'center',
  },
  teacherImageShadow: {
    height: 20 * vh,
    width: 20 * vh,
    borderRadius: 10.0 * vh,
    borderWidth: 1.5 * vw,
    borderColor: 'white',
    backgroundColor: 'white',
    elevation: 10,
  },
  teacherImageShadow2: {
    height: 4.0 * vh,
    width: 4.0 * vh,
    borderRadius: 2.0 * vh,
    borderWidth: 0.6 * vw,
    borderColor: 'green',
    backgroundColor: 'white',
    marginRight: 35 * vw,
  },

  teacherImage: {
    height: '100%',
    width: '100%',
    borderRadius: 10.0 * vh,
  },
  tick: {
    height: '100%',
    width: '100%',
    borderWidth: 0.2 * vw,
    borderRadius: 1.8 * vh,
    borderColor: 'white',
  },
  teacherName: {
    fontSize: 16,
    color: 'black',
    marginTop: 5 * vh,
  },
  coachingName: {
    fontSize: 13,
    color: 'black',
    opacity: 0.75,
  },
  pleaseSignInWith: {
    marginTop: 10 * vh,
    width: 100 * vw,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    padding: 5 * vw,
    opacity: 0.75,
  },
  horizontalLine: {
    height: 1,
    flex: 1,
    borderTopWidth: 1,
    borderTopColor: 'black',
  },
  pleaseSignInWithText: {
    fontSize: 3.5 * vw,
    margin: 2.5 * vw,
  },
  introTextContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 80 * vw,
  },
  introTextContainerForAutoSignin: {
    marginTop: vh * 0.3,
    justifyContent: 'center',
    alignItems: 'center',
    width: 80 * vw,
  },
  introTitle: {
    fontSize: 6 * vw,
    fontWeight: 'bold',
    color: 'black',
    marginTop: 40 * vh,
  },
  introTitleForAutoSignin: {
    fontSize: 6 * vw,
    fontWeight: 'bold',
    color: 'black',
    marginTop: 50 * vh,
  },
  introParaForAutoSignin: {
    marginTop: vh,
    fontSize: 4 * vw,
    textAlign: 'center',
  },
  version: {
    fontSize: 4 * vw,
    textAlign: 'center',
    marginBottom: 5 * vh,
  },
  introPara: {
    marginTop: vh,
    fontSize: 4 * vw,
    textAlign: 'center',
  },
  loginWithGoogleButton: {
    marginTop: vh,
    height: 7.5 * vh,
    width: 66 * vw,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loginWithGoogleButtonText: {
    color: 'white',
    fontSize: 4 * vw,
    marginLeft: 7.5 * vw,
  },
  fieldsInputContainer: {
    flexDirection: 'row',
    width: 80 * vw,
    alignItems: 'center',
    marginBottom: 5 * vh,
  },
  fieldsIcons: {
    height: 4 * vh,
    width: 4 * vh,
    marginRight: 2.5 * vw,
    opacity: 0.75,
  },
  phoneSectionContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 15 * vh,
  },
  phoneIcon: {
    height: 33 * vw,
    width: 33 * vw,
    marginBottom: 5 * vh,
  },
  phoneNumberContainer: {
    width: 80 * vw,
    height: 7.5 * vh,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  countryCode: {
    fontSize: 4.5 * vw,
    fontWeight: 'bold',
    color: 'black',
    borderRightWidth: 0.25 * vw,
    borderRightColor: 'rgba(0,0,0,0.4)',
    paddingRight: 2 * vw,
    justifyContent: 'center',
    alignItems: 'center',
  },
  phoneNumberInput: {
    borderBottomWidth: 0.25 * vw,
    borderBottomColor: 'rgba(0,0,0,0.4)',
    flex: 1,
    marginLeft: 2 * vw,
    fontSize: 4.5 * vw,
    paddingLeft: 2 * vw,
  },
  phoneNumberMessage: {
    fontSize: 3.75 * vw,
    width: 80 * vw,
    textAlign: 'center',
    color: 'black',
    marginTop: 4 * vh,
  },
  otpSectionContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 15 * vh,
  },
  otpTitle: {
    fontSize: 6 * vw,
    color: 'white',
  },
  otpSubTitle: {
    fontSize: 3.75 * vw,
    textAlign: 'center',
    color: 'white',
    width: '75%',
    marginTop: 2.5 * vh,
  },
  sentOTPButton: {
    marginTop: 40 * vh,
  },
  backgroundImage: {
    height: '100%',
    width: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  timeLeft: {
    color: 'white',
    fontSize: 3.75 * vw,
    marginTop: 2 * vh,
    marginBottom: 2 * vh,
  },
  submitOTPButton: {
    marginTop: 30 * vh,
    backgroundColor: '#b26df2',
    borderRadius: 3.75 * vh,
    height: 7.5 * vh,
    elevation: 2,
  },
  otpRetryButton: {
    marginTop: vh,
    marginBottom: vh,
    height: 7.5 * vh,
    width: 66 * vw,
    paddingTop: 1.5 * vh,
    paddingBottom: 1.5 * vh,
    justifyContent: 'center',
    alignItems: 'center',
  },
  otpRetryButtonText: {
    color: 'white',
    fontSize: 4 * vw,
    backgroundColor: '#b26df2',
    borderRadius: 3.75 * vh,
  },
  teachersSelectNextButton: {
    position: 'absolute',
    bottom: 3.5 * vh,
    right: 10 * vw,
    height: 7.5 * vh,
    width: 7.5 * vh,
    backgroundColor: 'rgba(255,255,255,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 3.75 * vh,
  },
  teachersSelectNextButtonIcon: {
    height: 5 * vh,
    width: 5 * vh,
  },
  pageTitle: {
    fontSize: 3.5 * vh,
    color: '#333',
    marginTop: 2.5 * vh,
    textAlign: 'center',
    elevation: 3,
    fontFamily: 'Montserrat-Medium',
  },
  logo: {
    backgroundColor: 'rgba(0,0,0,0)',
    width: 3.5 * vh,
    height: 3.5 * vh,
    marginLeft: 30 * vw,
    marginBottom: 4 * vh,
  },
  arrow: {
    height: 3 * vh,
    width: 3 * vh,
    marginTop: 4 * vh,
  },
});

export default styles;