import {Dimensions, StyleSheet} from 'react-native';

const screen = Dimensions.get('window'),
  vh = screen.height / 100,
  vw = screen.width / 100;

const styles = StyleSheet.create({
  animatedContainer: {
    height: 112 * vh,
    width: 100 * vw,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    zIndex: 1000,
  },
  container: {
    height: 106 * vh,
    width: 100 * vw,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    zIndex: 1000,
    top: 6 * vh,
    paddingTop: 22.5 * vh,
  },
  normalContainer: {
    height: 100 * vh,
    width: 100 * vw,
    backgroundColor: 'white',
    top: 6 * vh,
    left: 0,
    zIndex: 10000,
  },
  flexContainer: {
    flex: 1,
    width: 100 * vw,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backToMainButton: {
    flexDirection: 'row',
    position: 'absolute',
    bottom: 0,
    width: 100 * vw,
    height: 10 * vh,
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    paddingTop: 1.5 * vh,
    paddingBottom: 1.5 * vh,
    paddingLeft: 5 * vw,
    paddingRight: 5 * vw,
    margin: vh,
    width: 80 * vw,
    backgroundColor: 'rgba(0,0,0,0.15)',
  },
  button: {
    paddingTop: 2 * vh,
    paddingBottom: 2 * vh,
    paddingLeft: 5 * vw,
    marginLeft: vw,
    marginRight: vw,
    marginBottom: vh,
    width: 40 * vw,
    backgroundColor: 'black',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  largeButton: {
    width: 75 * vw,
    height: 17.5 * vh,
    borderRadius: 2.5 * vw,
    overflow: 'hidden',
    marginTop: 2 * vh,
    marginBottom: 2 * vh,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
  },
  largeButtonText: {
    fontSize: 5 * vw,
    zIndex: 100,
    position: 'absolute',
    left: 27.5 * vw,
  },
  picture: {
    height: 40 * vw,
    width: 40 * vw,
    borderRadius: 5 * vw,
    marginTop: -10 * vh,
    marginBottom: 5 * vh,
  },
  sectionHeader: {
    fontSize: 5 * vw,
    width: 60 * vw,
    position: 'absolute',
    top: 2.75 * vh,
    color: 'white',
    textAlign: 'center',
    fontFamily: 'Montserrat-SemiBold'
  },
  playStats: {
    flexDirection: 'row',
    width: 75 * vw,
    height: 8 * vh,
    position: 'absolute',
    top: 11 * vh,
  },
  playStatContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  playStatValue: {
    fontSize: 5 * vw,
    fontWeight: 'bold',
    color: 'white',
  },
  playStatSuffix: {
    fontSize: 3 * vw,
    margin: vw,
    color: 'white',
  },
  playStatLabel: {
    fontSize: 3.5 * vw,
    color: 'white',
  },
  playPull: {
    width: '100%',
    height: 12 * vh,
    position: 'absolute',
    top: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  playPullText: {
    fontSize: 5 * vw,
    color: 'white',
  },
  playPullImage: {
    height: '60%',
    width: '100%',
  },
  bottomLine: {
    position: 'absolute',
    height: vh,
    width: 100 * vw,
    backgroundColor: '#991bf1'
  },
  backgroundImage: {
    height: '100%',
    width: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  loadingInfoContainer: {
    marginTop: 10 * vh,
    flexDirection: 'row',
    height: 30 * vh,
    width: 100 * vw,
  },
  topLeftPlayer: {
    marginTop: 10 * vh,
    marginLeft: 10 * vw,
    height: 22 * vw,
    width: 22 * vw,
    borderRadius: 11 * vw,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white'
  },
  bottomRightPlayer: {
    position: 'absolute',
    marginTop: 10 * vh,
    marginLeft: 70 * vw,
    height: 22 * vw,
    width: 22 * vw,
    borderRadius: 11 * vw,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white'
  },
  profilePicture: {
    
    height: 20 * vw,
    width: 20 * vw,
    borderRadius: 10 * vw,
  },
  userNameLoading: {
    fontSize: 4 * vw,
    color: 'black',
    marginTop: 1.5 * vh,
  },
  nameTextContainer: {
    height: 5 * vh,
    width: 40 * vw,
    marginTop: 25 * vh,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',    
  },
  opponentNameTextContainer: {
    height: 5 * vh,
    width: 40 * vw,
    marginTop: 25 * vh,
    marginLeft: 60 * vw,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
  },
  centerVS: {
    marginTop: 15 * vh,
    marginLeft: 15 * vw,
    fontSize: 5 * vw,
    color: 'white',
    fontWeight: 'bold',
    
  },
  backIcon: {
    position: 'absolute',
    top: 10 * vw,
    left: 6 * vw,
    height: 6 * vw,
    width: 6 * vw,
    zIndex: 10
  },
  questionNumberContainer: {
    width: 100 * vw,
    height: 30 * vh,
    position: 'absolute',
    top: 10 * vh,
    justifyContent: 'center',
    alignItems: 'center',
  },
  questionNumberTitle: {
    fontSize: 7 * vw,
    color: 'white',
    position: 'absolute',
    top: 0,
    left: 0,
    marginLeft: 10 * vw,
    marginTop: 2.5 * vh,
  },
  questionNumberToggleContainer: {
    flexDirection: 'row',
    width: 60 * vw,
  },
  questionNumberToggle: {
    flex: 1,
    height: 7.5 * vh,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
  },
  leftBorder: {
    borderTopLeftRadius: 3.75 * vh,
    borderBottomLeftRadius: 3.75 * vh,
  },
  rightBorder: {
    borderTopRightRadius: 3.75 * vh,
    borderBottomRightRadius: 3.75 * vh,
  },
  active: {
    backgroundColor: '#C771E5',
  },
  questionNumberToggleText: {
    fontSize: 7.5 * vw,
    color: '#C771E5',
  },
  activeText: {
    color: 'white',
  },
  connectWith: {
    height: 45 * vh,
    width: 90 * vw,
    marginLeft: 5 * vw,
    backgroundColor: 'white',
    borderRadius: 5 * vw,
    position: 'absolute',
    bottom: 15 * vh,
    elevation: 5,
  },
  challengeButton: {
    position: 'absolute',
    height: 8 * vh,
    width: 66 * vw,
    marginLeft: 16 * vw,
    backgroundColor: '#a673db',
    borderRadius: 4 * vh,
    zIndex: 10,
    elevation: 5,
    bottom: 11 * vh,
    justifyContent: 'center',
    alignItems: 'center',
  },
  challengeButtonText: {
    color: 'white',
    fontSize: 6.66 * vw,
  },
  connectWithTitle: {
    fontSize: 6 * vw,
    color: 'black',
    marginTop: 4 * vh,
    marginLeft: 7.5 * vw,
  },
  activityIndicator: {
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 11 * vw,
    marginTop: 5 *  vh,
    height: 10*vh,
    width: 15 * vw,
    
  },
  contactContainer: {
    height: 35 * vw,
    width: 25 * vw,
    marginTop: 2.5 * vh,
    marginLeft: vw,
    marginRight: vw,
    justifyContent: 'center',
    alignItems: 'center',
  },
  contactImage: {
    height: 20 * vw,
    width: 20 * vw,
    borderWidth: vw,
    borderColor: '#CACFD0',
    borderRadius: 12.5 * vw,
  },
  contactName: {
    fontSize: 4 * vw,
    color: 'black',
    marginTop: 2 * vw,
  },
  playerContainer: {
    width: 90 * vw,
    height: 50 * vh,
    position: 'absolute',
    top: 10 * vh,
    flexDirection: 'row',
    elevation: 5,
  },
  playerStats: {
    flex: 1,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  statsFieldContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  userName: {
    color: 'white',
    fontSize: 5 * vw,
    marginTop: vh,
    marginBottom: 3 * vh,
    textAlign: 'center',
  },
  focusText: {
    fontSize: 7 * vw,
    color: 'white',
  },
  notFocusText: {
    fontSize: 4 * vw,
    color: 'white',
    marginBottom: vw,
    marginLeft: 0.5 * vw,
  },
  resultsInfo: {
    height: 20 * vh,
    width: 75 * vw,
    backgroundColor: 'white',
    borderBottomLeftRadius: 5 * vw,
    borderBottomRightRadius: 5 * vw,
    position: 'absolute',
    top: 55 * vh,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  resultsInfoImage: {
    flex: 1,
    height: 25 * vw,
    marginLeft: 5 * vw,
  },
  resultsInfoText: {
    flex: 2,
    fontSize: 5 * vw,
    textAlign: 'center',
    color: 'black',
  },
  rematchButton: {
    position: 'absolute',
    bottom: 7.5 * vh,
    height: 12.5 * vh,
    width: 65 * vw,
    justifyContent: 'center',
    alignItems: 'center',
  },
  rematchText: {
    color: 'white',
    fontSize: 7 * vw,
    marginRight: 12.5 * vw,
  },
  topNav: {
    width: 100 * vw,
    height: 10 * vh,
    elevation: 1,
    position: 'absolute',
    top: 0,
    backgroundColor: '#f5f5f5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  topNavTitle: {
    fontSize: 6 * vw,
    elevation: 10,
    fontFamily: 'Montserrat-Medium',
    color: 'black',
  },
  topNavTitleSecondLine: {
    fontSize: 4 * vw,
    elevation: 10,
    fontFamily: 'Montserrat-Medium',
    color: 'black',
  },
  bodyTextContainer: {
    height: 5 * vh,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bodyTextContainer1: {
    height: 20 * vh,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  startButton: {
    height: 5 * vh,
    width: 10 * vw,
    borderRadius: 4 * vh,
    borderColor: 'blue'
  },
  fix: {},
});

export default styles;