import {Dimensions, StyleSheet} from 'react-native';

const screen = Dimensions.get('window'),
  vh = screen.height / 100,
  vw = screen.width / 100;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    width: 100 * vw,
    height: 100 * vh,
    backgroundColor: '#f5f5f5',
  },
  performanceContainer: {
    flex: 1,
    height: 100 * vw,
    width: 100 * vw,
    backgroundColor: '#6500be',
  },
  challengeTopSection: {
    height: 45 * vh,
    width: 80 * vw,
    borderRadius: 2 * vw,
    backgroundColor: 'white',
    elevation: 2,
    alignItems: 'center',
  },
  nextButton: {
    height: 7 * vh,
    width: '100%',
    bottom: 0,
    position: 'absolute',
    elevation: 6,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#7741cd'
  },
  challengeTopSectionText: {
    flex: 1,
    fontSize: 4.5 * vw,
    marginRight: 2 * vh,
    marginLeft: 2 * vh,
    marginTop: 2 * vh,
    fontFamily: 'Montserrat-SemiBold',
    paddingLeft: 3 * vw,
    paddingRight: 3 * vw,
    color: 'black',
    justifyContent: 'center',
    alignItems: 'center',
  },
  challengeAcceptText: {
    paddingLeft: 10 * vw,
    paddingRight: 10 * vw,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  challengeAcceptText1: {
    paddingLeft: 10 * vw,
    paddingRight: 10 * vw,
    flexDirection: 'row',
    marginTop: 20 * vh,
    justifyContent: 'center',
    alignItems: 'center',
  },
  playerStats: {
    flex: 1,
    height: '100%',
    alignItems: 'center',
    marginTop: 2 * vh,
  },
  profilePicture: {
    height: 20 * vw,
    width: 20 * vw,
    borderRadius: 10 * vw,
  },
  userName: {
    color: 'black',
    fontSize: 4 * vw,
    marginTop: 1 * vh,
    textAlign: 'center',
  },
  statsFieldContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginBottom: 2 * vh,
  },
  focusText: {
    fontSize: 6 * vw,
    color: 'black',
  },
  notFocusText: {
    fontSize: 4 * vw,
    color: 'black',
    marginBottom: vw,
    marginLeft: 0.5 * vw,
  },
  topNav: {
    width: 100 * vw,
    height: 10 * vh,
    position: 'absolute',
    top: 0,
    backgroundColor: '#f5f5f5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backIcon: {
    height: 5 * vh,
    width: 5 * vh,
    marginLeft: 10 * vw - 2.5 * vh,
    transform: [{rotateZ: '180deg'}],
    position: 'absolute',
    left: 0,
  },
  notificationIcon: {
    height: 4 * vh,
    width: 4 * vh,
    marginRight: 10 * vw - 2 * vh,
    position: 'absolute',
    right: 0,
  },
  pageTitle: {
    fontSize: 3.5 * vh,
    color: '#333',
    marginTop: 2.5 * vh,
    textAlign: 'center',
    elevation: 3,
    fontFamily: 'Montserrat-Medium',
  },
  durationContainer: {
    height: 12 * vh,
    width: 85 * vw,
    marginTop: 2 * vh,
    paddingLeft: 7.5 * vw
  },
  sectionTitle: {
    fontSize: 3 * vh,
    color: 'black',
  },
  nextPage: {
    height: 9 * vh,
    marginTop: 4 * vh,
    alignSelf: 'center',
    width: 9 * vh,
    borderRadius: 4.5 * vh,
    justifyContent: 'center',
    alignItems: 'center',
  },
  nextPageIcon: {
    height: '100%',
    width: '100%',
  },
  toggleWrapper: {
    width: '100%',
    height: 6 * vh,
    marginTop: 2 * vh,
    alignSelf: 'center',
    flexDirection: 'row',
    
  },
  durationToggle: {
    height: '85%',
    // flex: 1,
    marginRight: '0%',
    width: 40 * vw,
    marginRight: '5%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'indigo',
  },
  activeToggle: {
    // backgroundColor: 'indigo',
    borderWidth: 0,
  },
  durationToggleText: {
    color: 'black',
    fontSize: 2.35 * vh,
    fontFamily: 'Montserrat-Medium',
  },
  activeToggleText: {
    color: 'white'
  },
  goalContainer: {
    height: 30 * vh,
    width: 100 * vw,
    marginTop: 1 * vh,
    paddingLeft: 7.5 * vw,
  },
  goalWrapper: {
    position: 'absolute',
    top: 20,
  },
  goalCardWrapper: {
    marginTop: 2.5 * vh,
    height: 24 * vh,
    justifyContent: 'center',
    alignItems: 'center',
  },
  goalCard: {
    height: 22 * vh,
    width: 22 * vh,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    borderRadius: 2 * vw,
  },
  selectedCardIconContainer: {
    position: 'absolute',
    height: 2.5 * vh,
    width: 2.5 * vh,
    top: 0,
    right: 0,
    margin: vh,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'grey',
    borderRadius: 2 * vh,
  },
  selectedCardIcon: {
    height: 3 * vh,
    width: 3 * vh,
    backgroundColor: 'green',
    borderRadius: 1.5 * vh

  },
  goalImage: {
    height: 10 * vh,
    width: 10 * vh,
    // borderRadius: 5 * vh,
    marginBottom: 1 * vh,
  },
  goalName: {
    fontSize: 3.35 * vw,
    color: 'black',
    marginTop: 10,
    borderWidth: 1,
    borderColor: 'indigo',
    padding: 4,
    borderRadius: 100,
    width: '85%',
    textAlign: 'center',
  },
  ongoingTest: {
    height: 90 * vh,
    marginTop: 10 * vh,
    width: 100 * vw,
  },
  questionNavigator: {
    height: 5 * vh,
    marginTop: 2.5 * vh,
    marginBottom: 2.5 * vh,
    width: '100%',
  },
  qaWrapper: {
    flex: 1,
    width: '100%',
  },
  optionsContainer: {
    width: '100%',
    marginTop: '5%',
    paddingBottom: '15%',
  },
  option: {
    position: 'relative',
    width: '90%',
    marginLeft: '5%',
    marginTop: '0%',
    paddingTop: '2.5%',
    paddingBottom: '2.5%',
    minHeight: 10 * vh,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
  },
  textContainer: {
    width: '90%',
    backgroundColor: 'white',
    elevation: 5,
    borderRadius: 12,
    padding: '5%',
    paddingLeft: '7.5%',
    paddingRight: '7.5%',
  },
  optionLabelExtension: {
    height: 5 * vh,
    width: '10%',
    backgroundColor: 'white',
    borderTopLeftRadius: 3 * vh,
    borderBottomLeftRadius: 3 * vh,
    elevation: 5,
    paddingLeft: 0.5 * vh,
    justifyContent: 'center',
  },
  labelWrapper: {
    backgroundColor: '#eee',
    borderRadius: 2 * vh,
    height: 4 * vh,
    width: 4 * vh,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(0,0,0,0.5)',
  },
  answerText: {
    fontSize: 2.5 * vh,
  },
  questionWrapper: {
    width: '90%',
    marginLeft: '5%',
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  questionText: {
    fontSize: 2.5 * vh,
    flex: 1,
  },
  questionTitle: {
    fontSize: 2.5 * vh,
    fontWeight: 'bold',
    marginRight: 5,
  },
  navigatorItem: {
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  navigatorItemText: {
    fontSize: 4 * vh,
    color: '#6867f2',
    fontFamily: 'Roboto'
  },
  navigatorPrevious: {
    position: 'absolute',
    top: 0,
    left: 0,
    height: '100%',
    width: 12.5 * vw,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navigatorNext: {
    position: 'absolute',
    top: 0,
    right: 0,
    height: '100%',
    width: 12.5 * vw,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navigatorButtonText: {
    fontSize: 32,
  },
  nextQuestionWrapper: {
    height: 7.5 * vh,
    width: 100 * vw,
    justifyContent: 'flex-end',
    alignItems: 'center',
    position: 'absolute',
    bottom: -0.5 * vh,
    zIndex: 1000000000000000000000000000000000000,
    elevation: 100000000000000000000000000000000,
  },
  nextQuestion: {
    width: 55 * vw,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 1000000000000000000,
  },
  nextQuestionText: {
    fontSize: 20,
    color: 'white',
  },
  testPerformanceReview: {
    height: 100 * vh,
    paddingTop: 10 * vh,
    width: 100 * vw,
  },

  // --------------------------------------------------------------------------------------------------------

  performanceOffset: {
    height: 50 * vh,
    width: 75 * vw,
    position: 'absolute',
    right: 0,
    top: 25 * vh,
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  pointsContainer: {
    backgroundColor: '#5e4096',
    height: 38 * vw,
    width: 38 * vw,
    borderRadius: 19 * vw,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pointsScoreContainer: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pointScoreValue: {
    fontSize: 10 * vw,
    color: 'white',
    fontWeight: 'bold',
  },
  pointScoreTitle: {
    fontSize: 4 * vw,
    marginTop: -2 * vw,
    color: 'white',
    textAlign: 'center',
  },
  circularIndicatorBackground: {
    backgroundColor: '#7751bc',
    position: 'absolute',
    height: 33.33 * vw,
    width: 33.33 * vw,
    borderRadius: 16.66 * vw,
  },
  tickContainer: {
    backgroundColor: 'white',
    height: 5 * vw,
    width: 5 * vw,
    position: 'absolute',
    zIndex: 10,
    top: 31.915 * vw,
    borderRadius: 2.5 * vw,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tickIcon: {
    height: 3.5 * vw,
    width: 3.5 * vw,
  },
  timeIndicator: {
    height: 5 * vh,
    width: 45 * vw,
    flexDirection: 'row',
    borderRadius: 2.5 * vh,
  },
  timeIndicatorIconWrapper: {
    flex: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  timeIndicatorIcon: {
    height: 2.75 * vh,
    width: 2.75 * vh,
  },
  timeIndicatorTextWrapper: {
    flex: 6,
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingLeft: 4 * vw,
  },
  timeIndicatorText: {
    fontSize: 2.75 * vh,
    color: 'white',
  },
  statsContainer: {
    flexDirection: 'row',
    width: 75 * vw,
  },
  statItem: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stat: {
    fontSize: 3 * vh,
    color: 'white',
  },
  statLabel: {
    color: 'white',
    fontSize: 2 * vh,
  },
  statIcon: {
    height: 6 * vw,
    width: 6 * vw,
  },
  testControls: {
    flexDirection: 'row',
    position: 'absolute',
    bottom: 10 * vh,
    width: 100 * vw,
    height: 10 * vh,
    borderTopLeftRadius: 10 * vw,
    borderTopRightRadius: 10 * vw,
  },
  testControlButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  backToMainButton: {
    flexDirection: 'row',
    position: 'absolute',
    bottom: 0,
    width: 100 * vw,
    height: 10 * vh,
    alignItems: 'center',
    justifyContent: 'center',
  },
  testControlButtonText: {
    fontSize: 2.8 * vh,
    color: 'white',
  },
  backToMainButtonText: {
    fontSize: 2.8 * vh,
    color: 'white',
  },
  topicListWrapper: {
    width: 100 * vw,
  },
  topicsListItem: {
    flexDirection: 'row',
    height: 10 * vh,
    alignItems: 'center',
    paddingLeft: 2.5 * vh,
  },
  bullet: {
    width: 2.5 * vw,
    height: 2.5 * vw,
    borderRadius: 1.25 * vw,
    borderWidth: 0.5 * vw,
    borderColor: '#C596EC',
    marginRight: 4 * vw,
  },
  topicsListItemText: {
    fontSize: 4 * vw,
    color: 'black',
    fontFamily: 'Montserrat-Regular',
    flex: 1,
  },
  topicsListItemIconContainer: {
    height: 3 * vh,
    width: 3 * vh,
    marginRight: 5 * vw,
    marginLeft: 5 * vw,
    borderRadius: 1.5 * vh,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#222',
  },
  topicsListItemIcon: {
    height: 3 * vh,
    width: 3 * vh,
  },
  scoreContainer: {
    // marginTop: 2.5*vh,
    position: 'absolute',
    flexDirection: 'row',
    width: 50 * vw,
  },
  leftBig: {
    flex: 1,
    alignItems: 'flex-end',
  },
  leftBigText: {
    fontSize: 11 * vh,
    color: 'white',
    fontFamily: 'Roboto',
  },
  rightSplit: {
    justifyContent: 'center',
    flex: 1,
  },
  rightSplitText: {
    marginBottom: 0.075 * vh,
    fontFamily: 'Roboto',
  },
  rightSplitTextBottom: {
    color: 'white',
    fontSize: 4 * vh,
    marginLeft: 0.5 * vw,
    fontFamily: 'Roboto',
  },
  reviewTag: {
    height: 6 * vh,
    width: 45 * vw,
    marginBottom: 2 * vh,
    marginLeft: 12.5 * vw,
    justifyContent: 'flex-start',
    flexDirection: 'row',
    backgroundColor: 'indigo',
    alignItems: 'center',
    borderRadius: 3.75 * vh,
  },
  reviewTagIcon: {
    height: 4 * vh,
    width: 4 * vh,
    marginLeft: 1.25 * vh,
    marginRight: 1.5 * vh,
  },
  reviewTagText: {
    fontSize: 2.75 * vh,
    color: 'white',
  },
  continueButtonText: {
    fontSize: 3 * vh,
    color: 'white',
  },
  submitConfirmOverlay: {
    position: 'absolute',
    height: 100 * vh,
    width: 100 * vw,
    backgroundColor: 'rgba(0,0,0,0.5)',
    elevation: 10000,
    justifyContent: 'center',
    alignItems: 'center',
  },
  submitConfirmContainer: {
    height: 25 * vh,
    width: 80 * vw,
    backgroundColor: 'white',
    borderRadius: 5 * vw,
    overflow: 'hidden',
  },
  messageTextContainer: {
    flex: 2,
    width: 80 * vw,
    justifyContent: 'center',
    alignItems: 'center',
  },
  messageText: {
    fontSize: 5.5 * vw,
    color: 'black',
    textAlign: 'center',
    marginRight: 2 * vw,
    marginLeft: 2 * vw,
  },
  submitConfirmButtonsContainer: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#e0e0e0',
  },
  submitConfirmButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  submitConfirmButtonText: {
    fontSize: 5.5 * vw,
    fontFamily: 'Montserrat-Medium',
  },
  loadingTopSectionImage: {
    width: 100 * vw,
    position: 'absolute',
    height: 17.5 * vh,
    top: 0,
  },
  loadingTimeIndicator: {
    height: 6.66 * vh,
    width: 60 * vw,
    borderRadius: 3.33 * vh,
    marginTop: 5 * vh,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingTimeIndicatorText: {
    fontSize: 5 * vw,
    marginRight: 4 * vw,
    color: 'white',
    fontFamily: 'Montserrat-Medium',
  },
  loadingTimeIndicatorBackground: {
    height: '100%',
    width: '100%',
    position: 'absolute',
    top: 0,
  },
  currentConfigContainer: {
    flexDirection: 'row',
    width: 90 * vw,
    justifyContent: 'space-around',
  },
  loadingTopicsContainer: {
    width: 85 * vw,
    height: 40 * vh,
  },
  loadingTopicsHeader: {
    fontSize: 6 * vw,
    fontFamily: 'Montserrat-Medium',
    color: 'black',
    marginTop: vh,
    marginBottom: vh,
  },
  topicListItem: {
    backgroundColor: 'white',
    height: 7.5 * vh,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.1)',
    paddingLeft: 4 * vw,
    elevation: 10,
  },
  topicsScrollContainer: {
    borderRadius: vw,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.1)',
    overflow: 'hidden',
  },
  loadingAnimationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  fingerAnimation: {
    height: 10 * vh,
    width: 30 * vw,
    marginLeft: 20 * vw,
  },
  loadingAnimationText: {
    fontSize: 5 * vw,
    color: 'black',
    flex: 1,
  },
  gymSubmitBG: {
    position: 'absolute',
    top: 0,
    left: 0,
    height: '100%',
    width: '100%',
  },
  conceptPopupPatch: {
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    marginTop: 59 * vh,
    transform: [{scaleX: 0.85}, {scaleY: 0.85}],
  },
  conceptGymStatsContainer: {
    width: 80 * vw,
    flexDirection: 'row',
    position: 'absolute',
    justifyContent: 'center',
  },
  conceptStats: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  conceptStatsNumber: {
    fontSize: 5 * vw,
    color: '#9557c1',
    fontFamily: 'Montserrat-SemiBold',
  },
  conceptStatsLabel: {
    fontSize: 4 * vw,
    color: '#9557c1',
    marginTop: -0.5 * vh,
  },
});

export default styles;